### ISSUE TITLE
How to change the range of the random teleportation

### ISSUE THREAD

**Issue by VeineMineaurion** [gamerpotion/DarkRTP#1]
Hello , i'm currently using a world border with a radius of 10000 on my darkrpg server ,

however most of the player using the command to teleport automatically die when they get tp'ed outside of it ,

thanks for responding to my Question .

Veine

**Comment by gamerpotion** [comment]
> Hello , i'm currently using a world border with a radius of 10000 on my darkrpg server ,
> 
> however most of the player using the command to teleport automatically die when they get tp'ed outside of it ,
> 
> thanks for responding to my Question .
> 
> Veine

Hi, what version of the modpack are you using?  the code for the teleport changed in recent version

**Comment by Rav115** [comment]
sadly we haven't made config files so just open mod folder **darkrtp-1.0.2.jar** with rar or zip so you can edit it
then edit **darkrtptick.mcfunction** file this line
```
execute as @a[scores={darkrtp=1..}] at @s unless entity @s[nbt={ActiveEffects:[{Id:28}]}] run spreadplayers 0 0 0 9000 under 127 false @s
```
change the 9000 to something else you can also change the first 2 zeros to x and z cords where you want the center to be incase yours isnt at 0 0
![Screenshot_20221207_184931](https://user-images.githubusercontent.com/39887530/206240330-6539174e-a62f-41d1-a333-e67a5ba53b5f.png)
